- lib/exceptions.dart
> Add exceptions.

- lib/src/configuration.dart
- test/configuration_test.dart
> Convert Configuration.nodes to a Set instead of List.

- lib/src/configuration.dart
- test/configuration_test.dart
Related to #4 will be helpful in implementing the health checkup logic.
> Add Node.lastAccessTimestamp

- lib/src/api_call.dart
There is similar code being shared in all the functions atm and I can't think of any way to DRY that atm, will revisit it in the future.
> Implement delete, post, put and patch.

- pubspec.lock
- pubspec.yaml
- test/collections_test.dart
> Add collections_test.dart

- lib/src/collections.dart
- test/collections_test.dart
> Implemented Collections endpoint

- lib/src/api_call.dart
- test/api_call_test.dart
- test/config_factory.dart
Fix index out of range error in ApiCall._nextNode
Fix type mismatch when throwing custom exception in ApiCall._handleNodeResponse
Add tests to api_call_test.dart
Add config_factory.dart
> ApiCall update

- lib/src/operations.dart
- test/operations_test.dart
> Add Operations.

- lib/src/health.dart
- test/health_test.dart
> Add Health.

- lib/src/collections.dart
- lib/src/models/field.dart
- lib/src/models/schema.dart
- test/models/field_test.dart
- test/models/schema_test.dart
> Add Schema and Field.

- lib/src/api_call.dart
> Update ApiCall._nextNode() to ensure all nodes are utillized.

- lib/src/aliases.dart
- lib/src/api_call.dart
- lib/src/models/alias.dart
- test/aliases_test.dart
- test/models/alias_test.dart
> Add Aliases.

- lib/src/api_call.dart
- test/api_call_test.dart
> Add CONTENT_TYPE static field in ApiCall.

- lib/src/api_call.dart
- lib/src/documents.dart
- test/documents_test.dart
> Implementing Documents endpoint

- .circleci/config.yml
> Add test workflow from circleci sample.

- lib/src/multi_search.dart
- test/multi_search_test.dart
> Add MultiSearch.

- lib/src/models/field.dart
Adds `auto` to the `Type` enum.
> Update Field type.

- lib/src/models/field.dart
- test/models/field_test.dart
- test/models/schema_test.dart
> Update `Field` types according to `v0.20.0`

- pubspec.yaml
> Add description and homepage.

- lib/src/models/document.dart
- lib/src/services/api_call.dart
- lib/src/services/base_api_call.dart
- test/models/document_test.dart
- test/services/api_call_test.dart
- test/test_utils.dart
Add ApiCall.patch
Update BaseApiCall._API_KEY
> Add Document. (#42)

- lib/src/models/override.dart
- lib/src/overrides.dart
- test/models/override_test.dart
- test/overrides_test.dart
> Add Overrides and Override class (#46)

- lib/src/models/synonym.dart
- lib/src/synonyms.dart
- test/models/synonym.dart
- test/synonyms_test.dart
> Add Synonym and Synonyms class (#47).

- lib/src/models/collection.dart
- test/models/collection_test.dart
> Add Collection class (#48).

- lib/src/debug.dart
- test/debug_test.dart
> Implemented debug endpoint

- lib/src/configuration.dart
- lib/src/search_client.dart
- pubspec.yaml
- test/configuration_test.dart
- test/search_client_test.dart
Add `Configuration.updateParameters` constructor.
Add dependency on `collection` package.
> Add `SearchClient` (#55).

- lib/src/keys.dart
- lib/src/models/key.dart
- pubspec.yaml
- test/keys_test.dart
- test/models/key_test.dart
> Add `Key` and `Keys`.

- lib/typesense.dart
> Expose `SearchClient`.

- lib/src/documents.dart
- lib/src/exceptions/import_error.dart
- test/documents_test.dart
- test/exceptions_test.dart
Add Documents.importDocuments
Update Documents.importJsonlDocuments
Update ImportError
> Import Documents

- lib/src/search_client.dart
- test/search_client_test.dart
> Refactor `SearchClient`

- lib/src/document.dart
- lib/src/documents.dart
- lib/src/models/field.dart
- lib/src/models/schema.dart
- lib/src/multi_search.dart
- test/document_test.dart
- test/documents_test.dart
- test/models/schema_test.dart
Rename importJsonlDocuments() to importJSONL()
Rename exportJsonlDocuments() to exportJSONL()
Update Field to extend Equatable.
Update Schema.fromMap to set defaultSortingField to null,
if not found in fields.
> Add doc comments.

- example/console-simple/assets/documents.jsonl
- example/console-simple/bin/collections.dart
- example/console-simple/bin/documents.dart
- example/console-simple/bin/main.dart
- example/console-simple/bin/search.dart
- example/console-simple/bin/util.dart
- example/console-simple/pubspec.yaml
> Add Documents and Search example.

- example/console-simple/bin/collections.dart
- example/console-simple/bin/documents.dart
- example/console-simple/bin/search.dart
- example/console-simple/bin/util.dart
- lib/src/keys.dart
- lib/typesense.dart
- test/keys_test.dart
Made generateScopedSearchKey() member of Keys class.
> Update Keys class.

- example/console-simple/bin/collections.dart
- example/console-simple/bin/documents.dart
- example/console-simple/bin/keys.dart
- example/console-simple/bin/search.dart
- example/console-simple/main.dart
- lib/src/configuration.dart
- lib/src/key.dart
- lib/src/keys.dart
> Add Keys example and doc comments.

- lib/src/document.dart
- lib/src/documents.dart
- lib/src/services/api_call.dart
- lib/src/services/base_api_call.dart
- lib/src/services/collections_api_call.dart
- lib/src/services/documents_api_call.dart
- test/document_test.dart
- test/documents_test.dart
> Use null-aware operator to spread map instead of creating empty maps.

- example/console-simple/bin/keys.dart
- example/console-simple/bin/overrides.dart
- example/console-simple/bin/search.dart
- example/console-simple/main.dart
- lib/src/override.dart
- lib/src/overrides.dart
> Add doc comments and example for Curation.

- example/console-simple/bin/aliases.dart
- example/console-simple/main.dart
- lib/src/alias.dart
- lib/src/aliases.dart
> Add doc comments and example for Aliases.

- example/console-simple/bin/aliases.dart
- example/console-simple/bin/collections.dart
- example/console-simple/bin/keys.dart
- example/console-simple/bin/search.dart
- example/console-simple/bin/synonyms.dart
- example/console-simple/main.dart
- lib/src/synonym.dart
- lib/src/synonyms.dart
> Add doc comments and example for Synonyms.

- example/console-simple/main.dart
> Update main.dart according to #81.

- example/console-simple/bin/aliases.dart
- example/console-simple/bin/collections.dart
- example/console-simple/bin/documents.dart
- example/console-simple/bin/keys.dart
- example/console-simple/bin/overrides.dart
- example/console-simple/bin/search.dart
- example/console-simple/bin/synonyms.dart
- example/console-simple/bin/util.dart
- example/console-simple/main.dart
> Add writePropagationDelay() in utils.dart

- example/console-simple/bin/cluster_operations.dart
- example/console-simple/main.dart
- lib/src/operations.dart
- test/operations_test.dart
> Add doc comments and example for Cluster operations. (#68)

- .gitignore
- pubspec.yaml
> Make changes directed by `dart pub publish --dry-run`

- .circleci/config.yml
> Add `codecov` orb.

- example/console-simple/bin/main.dart
> Cosmetic change

- CONTRIBUTING.md
- README.md
- example/console-simple/README.md
> Update README.md and add CONTRIBUTING.md

- example/console-simple/README.md
- example/console-simple/bin/search.dart
- example/console-simple/server_configuration/node7108.ini
- example/console-simple/server_configuration/node8108.ini
- example/console-simple/server_configuration/node9108.ini
- lib/src/models/field.dart
- test/models/field_test.dart
> Add Type.geopoint

- example/console-simple/README.md
- example/console-simple/bin/documents.dart
- lib/src/documents.dart
- test/documents_test.dart
> Add `queryParams` to Documents.exportJSONL

- pubspec.yaml
> Update version in pubspec

- README.md
Added credits and Compatibility matrix
> Added credits and Compatibility matrix

- .circleci/config.yml
- example/console-simple/bin/collections.dart
- example/console-simple/bin/keys.dart
- example/console-simple/bin/search.dart
- example/console-simple/pubspec.lock
- lib/src/collection.dart
- lib/src/collections.dart
- lib/src/models/field.dart
- lib/src/models/schema.dart
- pubspec.yaml
- test/collections_test.dart
- test/models/schema_test.dart
Reverts typesense/typesense-dart#119
> Revert "Collection update."

- README.md
- test/client_test.dart
- test/search_client_test.dart
> chore: Update badges.

- CHANGELOG.md
- README.md
- pubspec.yaml
> Add example in readme.

- CHANGELOG.md
- README.md
- example/console-simple/bin/search.dart
- example/console-simple/pubspec.lock
- lib/src/models/field.dart
- pubspec.yaml
> Vector search #131

- CHANGELOG.md
- README.md
- example/console-simple/bin/main.dart
- example/console-simple/bin/presets.dart
- example/console-simple/pubspec.lock
- lib/src/client.dart
- lib/src/preset.dart
- lib/src/presets.dart
- pubspec.yaml
> Support `Presets` operations.

- lib/src/models/field.dart
- lib/src/models/schema.dart
- test/models/field_test.dart
- test/models/schema_test.dart
Add possibility to enable nested fields on schema
Add possibility to add fields with type object
> Enable nested fields
